# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

- job: 'Testing_bandersnatch_Mac'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36Lint:
        python.version: '3.6'
        toxenv: 'INTEGRATION'
      Python36:
        python.version: '3.6'
        toxenv: 'py36'
      Python37:
        python.version: '3.7'
        toxenv: 'py37'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Upgrade pip + setuptools'

  - script: python -m pip install .
    displayName: 'Install bandersnatch'

  - script: python test_runner.py
    displayName: 'Running test_runner for $(toxenv)'
