name: bandersnatch_docker_readme

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/docker_readme.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish README to Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.2.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: pypa/bandersnatch
